WARNING: $PATH does not agree with $PATH_modshare counter. The following directories' usage counters were adjusted to match. Note that this may mean that module unloading may not work correctly.
 /home/share/bin/ /home/applications/spack/applications/gcc-8.2.0/miniconda3-4.5.11-oqs2mbgv3mmo3dll2f2rbxt4plfgyqzv/bin /bin/
Traceback (most recent call last):
  File "/home/pvier002/3dbrain/run_3dbrain_pipeline.py", line 127, in <module>
    main(args.dataset, args.output_dir, args.sub_ids, args.work_dir)
  File "/home/pvier002/3dbrain/run_3dbrain_pipeline.py", line 100, in main
    wf.connect(subj_iterable, 'subject_id', comb, 'subject_id')
  File "/home/pvier002/miniconda3/envs/psb6351_env/lib/python3.8/site-packages/nipype/pipeline/engine/workflows.py", line 239, in connect
    raise Exception("\n".join(["Some connections were not found"] + infostr))
Exception: Some connections were not found
Module comb has no input called subject_id

